apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: national-parks-mongodb
customVersion: v1beta2
spec:
  v1beta2:
    image: habitatregistry.azurecr.io/jamesc/np-mongodb:latest
    count: 1
    service:
      name: np-mongodb
      topology: standalone
---
apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: national-parks-app
customVersion: v1beta2
spec:
  v1beta2:
    image: habitatregistry.azurecr.io/jamesc/national-parks:latest
    count: 2
    service:
      name: national-parks
      topology: standalone
      bind:
        - name: database
          service: np-mongodb
          group: default
---
apiVersion: v1
kind: Service
metadata:
  name: national-parks-lb
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 80
    targetPort: 8080
  selector:
    habitat-name: national-parks-app

