#!/bin/bash

set -x
exec 2>&1

env

INCAN=$(date +%s)

SECRET_FILENAME=$(mktemp)

export KUBERNETES_SERVICE_HOST
export KUBERNETES_SERVICE_PORT

TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
curl -ks -H "Authorization: Bearer ${TOKEN}" \
  https:${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}/api/v1/namespaces/default/secrets/{{cfg.secret_name}} \
  > ${SECRET_FILENAME}

if [ $? -ne 0 ]; then
  echo "Couldn't get secret {{cfg.secret_name}}"
  exit 1
fi

HOST=$(cat ${SECRET_FILENAME} |$(hab pkg path core/jq-static)/bin/jq -r .data.host|base64 -d)
PORT=$(cat ${SECRET_FILENAME} |$(hab pkg path core/jq-static)/bin/jq -r .data.port|base64 -d)
USERNAME=$(cat ${SECRET_FILENAME} |$(hab pkg path core/jq-static)/bin/jq -r .data.username|base64 -d)
PASSWORD=$(cat ${SECRET_FILENAME} |$(hab pkg path core/jq-static)/bin/jq -r .data.password|base64 -d)
DATABASE=$(cat ${SECRET_FILENAME} |$(hab pkg path core/jq-static)/bin/jq -r .data.database|base64 -d)
URI=$(cat ${SECRET_FILENAME} |$(hab pkg path core/jq-static)/bin/jq -r .data.uri|base64 -d)


FILENAME=$(mktemp)
cat << EOF > ${FILENAME}
[mysql]
host="${HOST}"
port="${PORT}"
username="${USERNAME}"
password="${PASSWORD}"
database="${DATABASE}"
uri="${URI}"
EOF

cat ${FILENAME}

hab config apply {{svc.service}}.{{svc.group}} ${INCAN} ${FILENAME}

echo "OSBA Proxy starting"

while true; do
  sleep {{cfg.sleep}}
  echo "Running..."
done
